name: main

on:
  push:
    branches:
      - main

jobs:
  post-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ["1.5.2"]
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno v${{ matrix.deno }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run script
        run: deno run --allow-net ./twitter.ts ${{ secrets.TWITTER_CONSUMER_API_KEY }} ${{ secrets.TWITTER_CONSUMER_API_SECRET }} ${{ secrets.TWITTER_ACCESS_TOKEN }} ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }} "New Drash version released! https://github.com/drashland/deno-drash/releases/latest"
