name: main

on:
  push:
    branches:
      - main

jobs:
  post-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: ["1.5.2"]
    steps:
      - uses: actions/checkout@v2

      - name: Install Deno v${{ matrix.deno }}
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}

      - name: Run script
        run: |
          echo "test"
